"""initial_schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-09-26 20:40:00.000000

"""
from alembic import op
import sqlalchemy as sa
from app.db import SCHEMA_PG

revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    bind = op.get_bind()
    sql = SCHEMA_PG
    if bind.dialect.name == "sqlite":
        sql = sql.replace("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT")
        sql = sql.replace("TIMESTAMPTZ", "TEXT").replace("BOOLEAN", "INTEGER")
        sql = sql.replace("DEFAULT FALSE", "DEFAULT 0").replace("DEFAULT TRUE", "DEFAULT 1")
    for stmt in sql.split(";"):
        stmt = stmt.strip()
        if stmt:
            op.execute(stmt)

def downgrade():
    pass

