from fastapi import APIRouter, Depends, HTTPException, status

from app.core.permissions import require_roles
from app.db import get_db

router = APIRouter(prefix='/api/progress', tags=['progress'])


@router.get('/weekly-report/{assignment_id}')
def generate_weekly_progress_report(assignment_id: int, user=Depends(require_roles('mentor', 'provider', 'intern'))):
    with get_db() as db:
        assignment = db.execute(
            '''SELECT ma.*,
                      u_intern.full_name AS intern_name, u_intern.email AS intern_email,
                      u_mentor.full_name AS mentor_name,
                      i.title AS internship_title
               FROM mentor_assignments ma
               JOIN users u_intern ON u_intern.id = ma.intern_id
               JOIN users u_mentor ON u_mentor.id = ma.mentor_id
               LEFT JOIN internships i ON i.id = ma.internship_id
               WHERE ma.id = ?''',
            (assignment_id,),
        ).fetchone()

        if not assignment:
            raise HTTPException(status_code=404, detail='Mentor assignment not found.')

        intern_id = assignment['intern_id']

        # Attendance stats
        att_row = db.execute(
            '''SELECT COUNT(*) AS days_present, COALESCE(SUM(work_minutes), 0) AS total_minutes
               FROM attendance WHERE intern_id = ? AND status = 'checked_out' ''',
            (intern_id,),
        ).fetchone()
        days_present = att_row['days_present'] or 0
        total_hours = round((att_row['total_minutes'] or 0) / 60.0, 1)

        # Task stats
        tasks = db.execute(
            'SELECT title, priority, status FROM mentor_tasks WHERE intern_id = ?',
            (intern_id,),
        ).fetchall()
        tot_tasks = len(tasks)
        comp_tasks = sum(1 for t in tasks if t['status'] == 'completed')
        submitted_tasks = sum(1 for t in tasks if t['status'] == 'submitted')

        # Milestones
        milestones = db.execute(
            '''SELECT gm.title, gm.status FROM goal_milestones gm
               JOIN internship_goals ig ON ig.id = gm.goal_id
               WHERE ig.assignment_id = ?''',
            (assignment_id,),
        ).fetchall()
        tot_milestones = len(milestones)
        comp_milestones = sum(1 for m in milestones if m['status'] == 'completed')

        # Skill observations
        observations = db.execute(
            '''SELECT mso.*, s.name AS skill_name FROM mentor_skill_observations mso
               JOIN skills s ON s.id = mso.skill_id
               WHERE mso.intern_id = ? ORDER BY mso.created_at DESC''',
            (intern_id,),
        ).fetchall()
        skills_obs_list = [f"{o['skill_name']} ({o['level']})" for o in observations]

    # Generate Markdown Summary
    report_markdown = f"""
# Weekly Internship Progress Report

**Intern:** {assignment['intern_name']}  
**Role:** {assignment['internship_title'] or 'Engineering Intern'}  
**Mentor:** {assignment['mentor_name']}  

---

### Executive Summary
{assignment['intern_name']} has completed **{comp_tasks} of {tot_tasks}** assigned tasks and **{comp_milestones} of {tot_milestones}** project milestones. Total logged attendance: **{total_hours} hours** across **{days_present} days**.

### Performance Highlights
- **Task Execution:** {comp_tasks} completed, {submitted_tasks} pending review.
- **Milestone Progress:** {comp_milestones}/{tot_milestones} completed.
- **Observed Skills:** {', '.join(skills_obs_list) if skills_obs_list else 'Developing core engineering skills.'}

---
*Generated by InternFlow AI Engine*
""".strip()

    return {
        'assignment_id': assignment_id,
        'intern_name': assignment['intern_name'],
        'internship_title': assignment['internship_title'],
        'summary': {
            'total_hours': total_hours,
            'days_present': days_present,
            'tasks_completed': comp_tasks,
            'total_tasks': tot_tasks,
            'milestones_completed': comp_milestones,
            'total_milestones': tot_milestones,
            'observed_skills': skills_obs_list,
        },
        'report_markdown': report_markdown,
    }
